---
title: WEEKLY CHERNYSHEV
timezone: America/Vancouver
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      src_image:
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

url: https://techec.github.io
baseurl: ''
description: Учебно-развлекательный портал Лаборатории ИПИ
navbar-links:
  ВЕЧЕРНЫШЕВ: https://www.youtube.com/user/ckpmipt
  Читать:
  - Категории: categories
  - Тэги: tags
  Наши люди: 
  Учи матчасть:
  - Книги: http://www.chernyshev.ru/publications/
  - Статьи: http://www.chernyshev.ru/publications/
  - Видеокурсы: https://www.youtube.com/user/ckpmipt
  - Видеосюжеты: https://www.youtube.com/playlist?list=PLjQl8DO6RxtcR1sdRECYNkLhKSXBATAJW
  - Проекты: http://www.chernyshev.ru/history/
  Автор: https://ru.wikipedia.org/wiki/Чернышев_Сергей_Борисович
avatar: "/img/avatar-icon.png"
navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"
author:
  name: WEEKLY CHERNYSHEV
social-network-links:
  rss: true
  email: yubeloborodov@gmail.com
  facebook: groups/property1
  youtube: ckpmipt
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: false
staticman:
  repository: 
  branch: 
  endpoint: 
  reCaptcha:
    siteKey: 
    secret: 
excerpt_length: 50
title-separator: "-"
markdown: kramdown
highlighter: rouge
permalink: "/:year-:month-:day-:title/"
paginate: 5
kramdown:
  input: GFM
link-tags: true
exclude:
- CHANGELOG.md
- CNAME
- Dockerfile
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- Vagrantfile
prose:
  rooturl: _posts
  media: img
  ignore:
  - 404.html
  - LICENSE
  - feed.xml
  - _config.yml
  - "/_layouts"
  - "/_includes"
  - "/css"
  - "/img"
  - "/js"
  metadata:
    _posts:
    - name: layout
      field:
        element: hidden
        value: post
    - name: title
      field:
        element: text
        label: Post title
        placeholder: Title
        alterable: true
    - name: subtitle
      field:
        element: textarea
        label: Subtitle
        placeholder: A description of your post.
        alterable: true
    - name: date
      field:
        element: text
        label: Date
        help: Enter date of post.
        placeholder: yyyy-mm-dd
        alterable: true
    - name: image
      field:
        element: text
        label: Image
        help: Add a thumbnail image to your post.
        placeholder: Thumbnail
        alterable: true
    - name: published
      field:
        element: checkbox
        label: Publish
        help: Check to publish post, uncheck to hide.
plugins:
- jekyll-paginate
- jekyll-sitemap
